/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as croudfundingTicketingSol from "./CroudfundingTicketing.sol";
export type { croudfundingTicketingSol };
export type { RewardToken } from "./RewardToken";
